### ISSUE TITLE
MySQL NewWithDatabaseInstance is returning a nil *migrate.Migrate with no error

### ISSUE THREAD

**Issue by Cagrosso** [golang-migrate/migrate#633]
**Describe the Bug**
I'm attempting to migrate a MySQL database.  Calling `migrate.NewWithDatabaseInstance` with my database returns a nil `migrate.Migrate` with no error.

**Steps to Reproduce**
My config for establishing a connection to MySQL docker container
```go
        config := mysql.Config{
		DBName:               os.Getenv("DB_NAME"),
		User:                 os.Getenv("DB_USER"),
		Passwd:               os.Getenv("DB_PASS"),
		Net:                  "tcp",
		Addr:                 fmt.Sprintf("%s:%s", os.Getenv("DB_HOST"), os.Getenv("DB_PORT")),
		AllowNativePasswords: true,
		MultiStatements:      true,
		ParseTime:            true,
		Loc:                  time.UTC,
	}

	db, err := sql.Open("mysql", config.FormatDSN())
	if err != nil {
		panic(err.Error())
	}
```

Migrations
```go
	migrationsLocation := os.Getenv("DB_MIGRATIONS")

	driver, err := mysqlMigrator.WithInstance(
		db,
		&mysqlMigrator.Config{DatabaseName: os.Getenv("DB_NAME")})
	if err != nil {
		panic(err.Error())
	}

	migrator, err := migrate.NewWithDatabaseInstance(
		"file://"+migrationsLocation,
		"mysql",
		driver,
	)

	if err = migrator.Up(); err != nil && err != migrate.ErrNoChange {
		fmt.Printf("blah blah blah")

	}
```

My issue stems from `migrator, err := migrate.NewWithDatabaseInstance()` line.  It returns with `migrator = nil` and `err = nil`

**Expected Behavior**
I expected an error with information as to why my NewWithDatabaseInstance was returning nil.

**Migrate Version**
v4.15.0

**Loaded Source Drivers**
e.g. s3, github, go-bindata, gcs, file
Obtained by running: `migrate -help`

**Loaded Database Drivers**
mysql

**Go Version**
go 1.17.1

**Stacktrace**
```
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x58 pc=0x11d499f]

goroutine 1 [running]:
github.com/golang-migrate/migrate/v4.(*Migrate).lock(0x0)
        .../golang-migrate/migrate/v4@v4.15.0/migrate.go:890 +0x3f
github.com/golang-migrate/migrate/v4.(*Migrate).Up(0x0)
        .../golang-migrate/migrate/v4@v4.15.0/migrate.go:268 +0x25
.../server/repository.migrateDatabase(0x12743a0)
        .../server/repository/repository.go:73 +0x205
.../server/repository.NewDatabaseConnection()
        .../server/repository/repository.go:46 +0x352
main.main()
        .../server/main.go:8 +0x19
exit status 2
```
note: removed path lines for privacy replace with (...). Project located within GOPATH

**Comment by Cagrosso** [comment]
Well I feel like a fool.  Too long staring at this code made me blind to the fact that I wasn't actually checking for the error returned.  The function was returning an error correctly, and I was able to resolve my issue with the error output.
